### ISSUE TITLE
When searching for a term, the editor shows up with unexpected information

### ISSUE THREAD

**Issue by katgironpe** [phrase/angular-phrase#1]
Scenario:

I search for "engine" and two results show up. 
I click on "engine" and I get unexpected or wrong text on Information tab. 

![PhraseApp](http://gifyu.com/images/phraseapp_bug.gif)

**Comment by katgironpe** [comment]
Clearly a UX issue because the key is not related to text returned in any way.

**Comment by docstun** [comment]
Thanks, we'll look into this.

**Comment by katgironpe** [comment]
Thank you!

**Comment by docstun** [comment]
We have fixed this issue, fix is going live soon :)

**Comment by docstun** [comment]
Fix is live. Can you confirm it works for you now?

**Comment by katgironpe** [comment]
@docstun It works great now! Thank you! :+1:

**Comment by katgironpe** [comment]
@docstun But we have shipped a different solution for translators so they could see changes without editing on their browser. For some reason, the key shows up but not the translation and that's a different issue for you to investigate. (I have yet to confirm but this is the reason why they gave a task this week to make sure translation changes are seen by a translator on a staging site).

**Comment by docstun** [comment]
@katgironpe could you please open a separate issue for that? Thanks.
