### ISSUE TITLE
Any update on directive support?

### ISSUE THREAD

**Issue by nathan-costa** [phrase/angular-phrase#2]
I see it is on your roadmap, is there an ETA at this point?

**Comment by docstun** [comment]
I just pushed an update to master that works for my test case. Can you confirm?

**Comment by nathan-costa** [comment]
Will do this in the morning, thanks!

**Comment by nathan-costa** [comment]
Hi,

not working for me I'm afraid. If I try to use the angular configuration I
get only the keys displayed with the prefix and suffix '{__ and __}'. If I
use the generic script in the head it works, but only for filters. The
translations inside directives are not visible at all on the page. Will try
get time to look more into it later, if you have anything you want me to
try, let me know?

Thanks

On 23 September 2015 at 19:12, Nathan Power <nathan@costadigital.io> wrote:

> Will do this in the morning, thanks!
> On 23 Sep 2015 7:09 pm, "Manuel Boy" <notifications@github.com> wrote:
>
>> I just pushed an update to master that works for my test case. Can you
>> confirm?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/phrase/angular-phrase/issues/2#issuecomment-142666036>
>> .
>>
>


-- 
__________________________________________________________


*Nathan Power*
*Software Developer*

Email: nathan.power@nearform.com
Cell / Mobile: +353 87 6921551
Skype: papillonirl

http://www.nearform.com
nearForm Limited, Tankfield, Convent Hill, Tramore,
Co. Waterford. Registered in Ireland as Company Reg. Number: 507692.

**Comment by docstun** [comment]
Could you share some code so that I can reproduce your case?

**Comment by nathan-costa** [comment]
Sure, gist created here:
https://gist.github.com/nathan-costa/9615f16a5a7d9d1cbb07

On 24 September 2015 at 15:13, Manuel Boy <notifications@github.com> wrote:

> Could you share some code so that I can reproduce your case?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phrase/angular-phrase/issues/2#issuecomment-142922699>
> .
>



-- 
__________________________________________________________


*Nathan Power*
*Software Developer*

Email: nathan.power@nearform.com
Cell / Mobile: +353 87 6921551
Skype: papillonirl

http://www.nearform.com
nearForm Limited, Tankfield, Convent Hill, Tramore,
Co. Waterford. Registered in Ireland as Company Reg. Number: 507692.

**Comment by docstun** [comment]
I see. The update only covers the use for angular-translate directives like this:

    <h1 translate="my.key"></h1>

Can you confirm if this works? Will make it easier to handle the remaining cases as well.

**Comment by nathan-costa** [comment]
Hi, yes I can confirm that directives work in the in-context editor for my
project when I change it to this format.

On 25 September 2015 at 14:55, Manuel Boy <notifications@github.com> wrote:

> I see. The update only covers the use for angular-translate directives
> like this:
>
> <h1 translate="my.key"></h1>
>
> Can you confirm if this works? Will make it easier to handle the remaining
> cases as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phrase/angular-phrase/issues/2#issuecomment-143230564>
> .
>



-- 
__________________________________________________________


*Nathan Power*
*Software Developer*

Email: nathan.power@nearform.com
Cell / Mobile: +353 87 6921551
Skype: papillonirl

http://www.nearform.com
nearForm Limited, Tankfield, Convent Hill, Tramore,
Co. Waterford. Registered in Ireland as Company Reg. Number: 507692.

**Comment by docstun** [comment]
I just pushed an update, this should also work for your original format. Could you check if that does the trick?

**Comment by nathan-costa** [comment]
Seems to be working now. Many thanks for addressing this so quickly Manuel,
much appreciated !

On 25 September 2015 at 15:52, Manuel Boy <notifications@github.com> wrote:

> I just pushed an update, this should also work for your original format.
> Could you check if that does the trick?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phrase/angular-phrase/issues/2#issuecomment-143243892>
> .
>



-- 
__________________________________________________________


*Nathan Power*
*Software Developer*

Email: nathan.power@nearform.com
Cell / Mobile: +353 87 6921551
Skype: papillonirl

http://www.nearform.com
nearForm Limited, Tankfield, Convent Hill, Tramore,
Co. Waterford. Registered in Ireland as Company Reg. Number: 507692.

**Comment by docstun** [comment]
Great to hear! I just released it as a new version, should be installable via bower, too.
