### ISSUE TITLE
Install via NPM

### ISSUE THREAD

**Issue by kikar** [phrase/angular-phrase#4]
Is there a reason why this package isn't available via NPM?

**Comment by docstun** [comment]
No specific reason, but thanks for the input - we'll consider that in the future.

**Comment by kikar** [comment]
Hi @docstun any news on this?

**Comment by docstun** [comment]
@kikar looks like you already published it? https://www.npmjs.com/package/angular-phrase

Would be great if you could make the user "phraseapp" the owner so we can update the package with the latest version. Thanks!

**Comment by kikar** [comment]
The use "phraseapp" is now owner of the package on NPM.
Please update it every time you update it on bower, it would be very useful for us 😄

**Comment by docstun** [comment]
Thanks for that - We've updated the package, please let me know if everything is fine!
