### ISSUE TITLE
Default translation on keys for languages without translation is giving 'null' causing site to hang up

### ISSUE THREAD

**Issue by jlevym** [phrase/angular-phrase#5]
this is the console image from our site where we have  missing translations and expect to get the default-english-translation, but get 'null'.  
The app can be found at : https://github.com/lergo , where lergo-ui is the front-end, and lergo-ri is the back-end. The framework is the "MEAN Stack"
The two languages that do not have missing translations (default: english and hebrew) work flawlessly. 
![image](https://cloud.githubusercontent.com/assets/15942228/21184477/575fd176-c215-11e6-8c0e-2b49b58200a9.png)

**Comment by docstun** [comment]
Thanks for sharing. This is a known limitation, since interpolation is not yet supported (see https://github.com/phrase/angular-phrase#todo).

Is there any way you can provide a pull-request or tests for this case?

**Comment by jlevym** [comment]
the cause of our issue was traced to include_empty_translation while downloading. thank you all for your help
