### ISSUE TITLE
Care to migrate this app to @angular?

### ISSUE THREAD

**Issue by nottinhill** [phrase/angular-phrase#8]
We need this for Angular 2+.

**Comment by docstun** [comment]
It's on our radar but there is no ETA for a new version of the adapter. We'll notify you when there are any news.

**Comment by schwooz** [comment]
Hi @nottinhill, 
You've requested the support for Angular 2+ for the In-Context-Editor. Could you tell us which library/libraries are you using, which we should support?

**Comment by docstun** [comment]
Just came across this issue and would like to mention that Angular 2+ support is available for quite a while: https://github.com/phrase/ngx-translate-phraseapp
